# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.oauthclientsredirecturis_api import OauthclientsredirecturisApi


class TestOauthclientsredirecturisApi(unittest.TestCase):
    """ OauthclientsredirecturisApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.oauthclientsredirecturis_api.OauthclientsredirecturisApi()

    def tearDown(self):
        pass

    def test_create_account_oauth_clients_redirect_uri(self):
        """
        Test case for create_account_oauth_clients_redirect_uri

        Create an OAuth Client Redirect URI record.
        """
        pass

    def test_delete_account_oauth_clients_redirect_uri(self):
        """
        Test case for delete_account_oauth_clients_redirect_uri

        Delete an OAuth Client Redirect URI record.
        """
        pass

    def test_get_account_oauth_clients_redirect_uri(self):
        """
        Test case for get_account_oauth_clients_redirect_uri

        Get details of an OAuth Client Redirect URI record.
        """
        pass

    def test_list_account_oauth_clients_redirect_uris(self):
        """
        Test case for list_account_oauth_clients_redirect_uris

        Get a list of OAuth Client Redirect URIs for an account.
        """
        pass


if __name__ == '__main__':
    unittest.main()
