# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.paymentmethods_api import PaymentmethodsApi


class TestPaymentmethodsApi(unittest.TestCase):
    """ PaymentmethodsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.paymentmethods_api.PaymentmethodsApi()

    def tearDown(self):
        pass

    def test_create_account_payment_method(self):
        """
        Test case for create_account_payment_method

        Create an individual payment method.
        """
        pass

    def test_delete_account_payment_method(self):
        """
        Test case for delete_account_payment_method

        Delete an individual payment method.
        """
        pass

    def test_get_account_payment_method(self):
        """
        Test case for get_account_payment_method

        Show details of an individual payment method.
        """
        pass

    def test_list_account_payment_methods(self):
        """
        Test case for list_account_payment_methods

        Get a list of payment methods for an account.
        """
        pass

    def test_patch_account_payment_method(self):
        """
        Test case for patch_account_payment_method

        Replace the status of an individual payment method.
        """
        pass


if __name__ == '__main__':
    unittest.main()
