# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.subaccountpricing_api import SubaccountpricingApi


class TestSubaccountpricingApi(unittest.TestCase):
    """ SubaccountpricingApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.subaccountpricing_api.SubaccountpricingApi()

    def tearDown(self):
        pass

    def test_create_account_subaccount_pricing(self):
        """
        Test case for create_account_subaccount_pricing

        Add a pricing plan to a subaccount.
        """
        pass

    def test_delete_account_subaccount_pricing(self):
        """
        Test case for delete_account_subaccount_pricing

        Delete a pricing plan from a subaccount.
        """
        pass

    def test_get_account_subaccount_pricing(self):
        """
        Test case for get_account_subaccount_pricing

        Get the details of a pricing plan for a subaccount.
        """
        pass

    def test_list_account_subaccount_pricing(self):
        """
        Test case for list_account_subaccount_pricing

        Get a list of pricing plans for a subaccount.
        """
        pass


if __name__ == '__main__':
    unittest.main()
