# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.voicemail_api import VoicemailApi


class TestVoicemailApi(unittest.TestCase):
    """ VoicemailApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.voicemail_api.VoicemailApi()

    def tearDown(self):
        pass

    def test_get_account_voicemail(self):
        """
        Test case for get_account_voicemail

        This service shows the details of an individual voicemail.
        """
        pass

    def test_list_account_voicemail(self):
        """
        Test case for list_account_voicemail

        Get a list of voicemail messages for an account.
        """
        pass

    def test_patch_account_voicemail(self):
        """
        Test case for patch_account_voicemail

        Update the is_new parameter in a voicemail record.
        """
        pass


if __name__ == '__main__':
    unittest.main()
