# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.oauth_api import OauthApi


class TestOauthApi(unittest.TestCase):
    """ OauthApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.oauth_api.OauthApi()

    def tearDown(self):
        pass

    def test_create_oauth_access_token(self):
        """
        Test case for create_oauth_access_token

        To create an access token via the /oauth/access-token API, an API user may choose any one of the grant types it supports: Authorization Code Grant, Client Credential Grant, Password Credential Grant or Refresh Token Grant.
        """
        pass

    def test_create_oauth_authorization(self):
        """
        Test case for create_oauth_authorization

        Create Authorization Code or Access Token.
        """
        pass

    def test_get_oauth_access_token(self):
        """
        Test case for get_oauth_access_token

        Retrieve details of an access token, such as scope, expiration and extension ID.
        """
        pass


if __name__ == '__main__':
    unittest.main()
