# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.sms_forwarding_params import SmsForwardingParams


class TestSmsForwardingParams(unittest.TestCase):
    """ SmsForwardingParams unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmsForwardingParams(self):
        """
        Test SmsForwardingParams
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.sms_forwarding_params.SmsForwardingParams()
        pass


if __name__ == '__main__':
    unittest.main()
