# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.oauthclients_api import OauthclientsApi


class TestOauthclientsApi(unittest.TestCase):
    """ OauthclientsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.oauthclients_api.OauthclientsApi()

    def tearDown(self):
        pass

    def test_delete_account_oauth_client(self):
        """
        Test case for delete_account_oauth_client

        Delete an individual OAuth client.
        """
        pass

    def test_get_account_oauth_client(self):
        """
        Test case for get_account_oauth_client

        Show details of an individual OAuth client.
        """
        pass

    def test_list_account_oauth_clients(self):
        """
        Test case for list_account_oauth_clients

        Get a list of OAuth clients for an account.
        """
        pass


if __name__ == '__main__':
    unittest.main()
