# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CreateListenerParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'event_type': 'str',
        'callbacks': 'list[CallbackObject]'
    }

    attribute_map = {
        'type': 'type',
        'event_type': 'event_type',
        'callbacks': 'callbacks'
    }

    def __init__(self, type=None, event_type=None, callbacks=None):
        """
        CreateListenerParams - a model defined in Swagger
        """

        self._type = None
        self._event_type = None
        self._callbacks = None

        if type is not None:
          self.type = type
        if event_type is not None:
          self.event_type = event_type
        if callbacks is not None:
          self.callbacks = callbacks

    @property
    def type(self):
        """
        Gets the type of this CreateListenerParams.
        Type of listener. Must be 'callback'

        :return: The type of this CreateListenerParams.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this CreateListenerParams.
        Type of listener. Must be 'callback'

        :param type: The type of this CreateListenerParams.
        :type: str
        """

        self._type = type

    @property
    def event_type(self):
        """
        Gets the event_type of this CreateListenerParams.
        Type of event to subscribe. 'call.new', 'call.update', 'call.complete'

        :return: The event_type of this CreateListenerParams.
        :rtype: str
        """
        return self._event_type

    @event_type.setter
    def event_type(self, event_type):
        """
        Sets the event_type of this CreateListenerParams.
        Type of event to subscribe. 'call.new', 'call.update', 'call.complete'

        :param event_type: The event_type of this CreateListenerParams.
        :type: str
        """

        self._event_type = event_type

    @property
    def callbacks(self):
        """
        Gets the callbacks of this CreateListenerParams.
        Array of Callback Objects.

        :return: The callbacks of this CreateListenerParams.
        :rtype: list[CallbackObject]
        """
        return self._callbacks

    @callbacks.setter
    def callbacks(self, callbacks):
        """
        Sets the callbacks of this CreateListenerParams.
        Array of Callback Objects.

        :param callbacks: The callbacks of this CreateListenerParams.
        :type: list[CallbackObject]
        """

        self._callbacks = callbacks

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreateListenerParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
