# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CreatePhoneNumberParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, phone_number=None, route=None, name=None, block_incoming=None, block_anonymous=None, caller_id=None, sms_forwarding=None, call_notifications=None):
        """
        CreatePhoneNumberParams - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'phone_number': 'object',
            'route': 'object',
            'name': 'str',
            'block_incoming': 'bool',
            'block_anonymous': 'bool',
            'caller_id': 'CallerIdPhoneNumber',
            'sms_forwarding': 'SmsForwardingParams',
            'call_notifications': 'CallNotifications'
        }

        self.attribute_map = {
            'phone_number': 'phone_number',
            'route': 'route',
            'name': 'name',
            'block_incoming': 'block_incoming',
            'block_anonymous': 'block_anonymous',
            'caller_id': 'caller_id',
            'sms_forwarding': 'sms_forwarding',
            'call_notifications': 'call_notifications'
        }

        self._phone_number = phone_number
        self._route = route
        self._name = name
        self._block_incoming = block_incoming
        self._block_anonymous = block_anonymous
        self._caller_id = caller_id
        self._sms_forwarding = sms_forwarding
        self._call_notifications = call_notifications

    @property
    def phone_number(self):
        """
        Gets the phone_number of this CreatePhoneNumberParams.
        Phone number

        :return: The phone_number of this CreatePhoneNumberParams.
        :rtype: object
        """
        return self._phone_number

    @phone_number.setter
    def phone_number(self, phone_number):
        """
        Sets the phone_number of this CreatePhoneNumberParams.
        Phone number

        :param phone_number: The phone_number of this CreatePhoneNumberParams.
        :type: object
        """

        self._phone_number = phone_number

    @property
    def route(self):
        """
        Gets the route of this CreatePhoneNumberParams.
        Route lookup object

        :return: The route of this CreatePhoneNumberParams.
        :rtype: object
        """
        return self._route

    @route.setter
    def route(self, route):
        """
        Sets the route of this CreatePhoneNumberParams.
        Route lookup object

        :param route: The route of this CreatePhoneNumberParams.
        :type: object
        """

        self._route = route

    @property
    def name(self):
        """
        Gets the name of this CreatePhoneNumberParams.
        Phone Name

        :return: The name of this CreatePhoneNumberParams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreatePhoneNumberParams.
        Phone Name

        :param name: The name of this CreatePhoneNumberParams.
        :type: str
        """

        self._name = name

    @property
    def block_incoming(self):
        """
        Gets the block_incoming of this CreatePhoneNumberParams.
        Block incoming calls

        :return: The block_incoming of this CreatePhoneNumberParams.
        :rtype: bool
        """
        return self._block_incoming

    @block_incoming.setter
    def block_incoming(self, block_incoming):
        """
        Sets the block_incoming of this CreatePhoneNumberParams.
        Block incoming calls

        :param block_incoming: The block_incoming of this CreatePhoneNumberParams.
        :type: bool
        """

        self._block_incoming = block_incoming

    @property
    def block_anonymous(self):
        """
        Gets the block_anonymous of this CreatePhoneNumberParams.
        Block anonymous calls

        :return: The block_anonymous of this CreatePhoneNumberParams.
        :rtype: bool
        """
        return self._block_anonymous

    @block_anonymous.setter
    def block_anonymous(self, block_anonymous):
        """
        Sets the block_anonymous of this CreatePhoneNumberParams.
        Block anonymous calls

        :param block_anonymous: The block_anonymous of this CreatePhoneNumberParams.
        :type: bool
        """

        self._block_anonymous = block_anonymous

    @property
    def caller_id(self):
        """
        Gets the caller_id of this CreatePhoneNumberParams.
        Caller ID object

        :return: The caller_id of this CreatePhoneNumberParams.
        :rtype: CallerIdPhoneNumber
        """
        return self._caller_id

    @caller_id.setter
    def caller_id(self, caller_id):
        """
        Sets the caller_id of this CreatePhoneNumberParams.
        Caller ID object

        :param caller_id: The caller_id of this CreatePhoneNumberParams.
        :type: CallerIdPhoneNumber
        """

        self._caller_id = caller_id

    @property
    def sms_forwarding(self):
        """
        Gets the sms_forwarding of this CreatePhoneNumberParams.
        SMS Forwarding Object, or NULL

        :return: The sms_forwarding of this CreatePhoneNumberParams.
        :rtype: SmsForwardingParams
        """
        return self._sms_forwarding

    @sms_forwarding.setter
    def sms_forwarding(self, sms_forwarding):
        """
        Sets the sms_forwarding of this CreatePhoneNumberParams.
        SMS Forwarding Object, or NULL

        :param sms_forwarding: The sms_forwarding of this CreatePhoneNumberParams.
        :type: SmsForwardingParams
        """

        self._sms_forwarding = sms_forwarding

    @property
    def call_notifications(self):
        """
        Gets the call_notifications of this CreatePhoneNumberParams.
        Call Notifications object

        :return: The call_notifications of this CreatePhoneNumberParams.
        :rtype: CallNotifications
        """
        return self._call_notifications

    @call_notifications.setter
    def call_notifications(self, call_notifications):
        """
        Sets the call_notifications of this CreatePhoneNumberParams.
        Call Notifications object

        :param call_notifications: The call_notifications of this CreatePhoneNumberParams.
        :type: CallNotifications
        """

        self._call_notifications = call_notifications

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreatePhoneNumberParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
