# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CreateMenuParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'greeting': 'object',
        'keypress_error': 'object',
        'allow_extension_dial': 'str',
        'keypress_wait_time': 'int',
        'timeout_handler': 'object',
        'options': 'list[object]'
    }

    attribute_map = {
        'name': 'name',
        'greeting': 'greeting',
        'keypress_error': 'keypress_error',
        'allow_extension_dial': 'allow_extension_dial',
        'keypress_wait_time': 'keypress_wait_time',
        'timeout_handler': 'timeout_handler',
        'options': 'options'
    }

    def __init__(self, name=None, greeting=None, keypress_error=None, allow_extension_dial=None, keypress_wait_time=None, timeout_handler=None, options=None):
        """
        CreateMenuParams - a model defined in Swagger
        """

        self._name = None
        self._greeting = None
        self._keypress_error = None
        self._allow_extension_dial = None
        self._keypress_wait_time = None
        self._timeout_handler = None
        self._options = None

        if name is not None:
          self.name = name
        if greeting is not None:
          self.greeting = greeting
        if keypress_error is not None:
          self.keypress_error = keypress_error
        if allow_extension_dial is not None:
          self.allow_extension_dial = allow_extension_dial
        if keypress_wait_time is not None:
          self.keypress_wait_time = keypress_wait_time
        if timeout_handler is not None:
          self.timeout_handler = timeout_handler
        if options is not None:
          self.options = options

    @property
    def name(self):
        """
        Gets the name of this CreateMenuParams.

        :return: The name of this CreateMenuParams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this CreateMenuParams.

        :param name: The name of this CreateMenuParams.
        :type: str
        """

        self._name = name

    @property
    def greeting(self):
        """
        Gets the greeting of this CreateMenuParams.

        :return: The greeting of this CreateMenuParams.
        :rtype: object
        """
        return self._greeting

    @greeting.setter
    def greeting(self, greeting):
        """
        Sets the greeting of this CreateMenuParams.

        :param greeting: The greeting of this CreateMenuParams.
        :type: object
        """

        self._greeting = greeting

    @property
    def keypress_error(self):
        """
        Gets the keypress_error of this CreateMenuParams.

        :return: The keypress_error of this CreateMenuParams.
        :rtype: object
        """
        return self._keypress_error

    @keypress_error.setter
    def keypress_error(self, keypress_error):
        """
        Sets the keypress_error of this CreateMenuParams.

        :param keypress_error: The keypress_error of this CreateMenuParams.
        :type: object
        """

        self._keypress_error = keypress_error

    @property
    def allow_extension_dial(self):
        """
        Gets the allow_extension_dial of this CreateMenuParams.

        :return: The allow_extension_dial of this CreateMenuParams.
        :rtype: str
        """
        return self._allow_extension_dial

    @allow_extension_dial.setter
    def allow_extension_dial(self, allow_extension_dial):
        """
        Sets the allow_extension_dial of this CreateMenuParams.

        :param allow_extension_dial: The allow_extension_dial of this CreateMenuParams.
        :type: str
        """

        self._allow_extension_dial = allow_extension_dial

    @property
    def keypress_wait_time(self):
        """
        Gets the keypress_wait_time of this CreateMenuParams.

        :return: The keypress_wait_time of this CreateMenuParams.
        :rtype: int
        """
        return self._keypress_wait_time

    @keypress_wait_time.setter
    def keypress_wait_time(self, keypress_wait_time):
        """
        Sets the keypress_wait_time of this CreateMenuParams.

        :param keypress_wait_time: The keypress_wait_time of this CreateMenuParams.
        :type: int
        """

        self._keypress_wait_time = keypress_wait_time

    @property
    def timeout_handler(self):
        """
        Gets the timeout_handler of this CreateMenuParams.

        :return: The timeout_handler of this CreateMenuParams.
        :rtype: object
        """
        return self._timeout_handler

    @timeout_handler.setter
    def timeout_handler(self, timeout_handler):
        """
        Sets the timeout_handler of this CreateMenuParams.

        :param timeout_handler: The timeout_handler of this CreateMenuParams.
        :type: object
        """

        self._timeout_handler = timeout_handler

    @property
    def options(self):
        """
        Gets the options of this CreateMenuParams.

        :return: The options of this CreateMenuParams.
        :rtype: list[object]
        """
        return self._options

    @options.setter
    def options(self, options):
        """
        Sets the options of this CreateMenuParams.

        :param options: The options of this CreateMenuParams.
        :type: list[object]
        """

        self._options = options

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CreateMenuParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
