# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OauthClientFull(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'client_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'client_name': 'client_name'
    }

    def __init__(self, id=None, client_name=None):
        """
        OauthClientFull - a model defined in Swagger
        """

        self._id = None
        self._client_name = None

        if id is not None:
          self.id = id
        if client_name is not None:
          self.client_name = client_name

    @property
    def id(self):
        """
        Gets the id of this OauthClientFull.
        Client ID

        :return: The id of this OauthClientFull.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this OauthClientFull.
        Client ID

        :param id: The id of this OauthClientFull.
        :type: int
        """

        self._id = id

    @property
    def client_name(self):
        """
        Gets the client_name of this OauthClientFull.
        Name of Client

        :return: The client_name of this OauthClientFull.
        :rtype: str
        """
        return self._client_name

    @client_name.setter
    def client_name(self, client_name):
        """
        Sets the client_name of this OauthClientFull.
        Name of Client

        :param client_name: The client_name of this OauthClientFull.
        :type: str
        """

        self._client_name = client_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OauthClientFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
