# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class OauthClientRedirectUriFull(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'client': 'OauthClientFull',
        'redirect_uri': 'RedirectUriFull'
    }

    attribute_map = {
        'id': 'id',
        'client': 'client',
        'redirect_uri': 'redirect_uri'
    }

    def __init__(self, id=None, client=None, redirect_uri=None):
        """
        OauthClientRedirectUriFull - a model defined in Swagger
        """

        self._id = None
        self._client = None
        self._redirect_uri = None

        if id is not None:
          self.id = id
        if client is not None:
          self.client = client
        if redirect_uri is not None:
          self.redirect_uri = redirect_uri

    @property
    def id(self):
        """
        Gets the id of this OauthClientRedirectUriFull.
        OAuth Client Redirect URI ID

        :return: The id of this OauthClientRedirectUriFull.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this OauthClientRedirectUriFull.
        OAuth Client Redirect URI ID

        :param id: The id of this OauthClientRedirectUriFull.
        :type: int
        """

        self._id = id

    @property
    def client(self):
        """
        Gets the client of this OauthClientRedirectUriFull.
        Client details

        :return: The client of this OauthClientRedirectUriFull.
        :rtype: OauthClientFull
        """
        return self._client

    @client.setter
    def client(self, client):
        """
        Sets the client of this OauthClientRedirectUriFull.
        Client details

        :param client: The client of this OauthClientRedirectUriFull.
        :type: OauthClientFull
        """

        self._client = client

    @property
    def redirect_uri(self):
        """
        Gets the redirect_uri of this OauthClientRedirectUriFull.
        Redirect URI details

        :return: The redirect_uri of this OauthClientRedirectUriFull.
        :rtype: RedirectUriFull
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """
        Sets the redirect_uri of this OauthClientRedirectUriFull.
        Redirect URI details

        :param redirect_uri: The redirect_uri of this OauthClientRedirectUriFull.
        :type: RedirectUriFull
        """

        self._redirect_uri = redirect_uri

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, OauthClientRedirectUriFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
