# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PatchVoicemailParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_new': 'str'
    }

    attribute_map = {
        'is_new': 'is_new'
    }

    def __init__(self, is_new=None):
        """
        PatchVoicemailParams - a model defined in Swagger
        """

        self._is_new = None

        if is_new is not None:
          self.is_new = is_new

    @property
    def is_new(self):
        """
        Gets the is_new of this PatchVoicemailParams.
        Status of voicemail

        :return: The is_new of this PatchVoicemailParams.
        :rtype: str
        """
        return self._is_new

    @is_new.setter
    def is_new(self, is_new):
        """
        Sets the is_new of this PatchVoicemailParams.
        Status of voicemail

        :param is_new: The is_new of this PatchVoicemailParams.
        :type: str
        """

        self._is_new = is_new

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PatchVoicemailParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
