# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PaymentFull(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'voip_id': 'int',
        'status': 'str',
        'nickname': 'str',
        'type': 'str',
        'created_at': 'int',
        'contact': 'ContactResponse',
        'decline_count': 'int',
        'next_charge_date': 'int',
        'updated_at': 'int',
        'cc_token': 'str',
        'cc_number': 'str',
        'cc_exp': 'str'
    }

    attribute_map = {
        'id': 'id',
        'voip_id': 'voip_id',
        'status': 'status',
        'nickname': 'nickname',
        'type': 'type',
        'created_at': 'created_at',
        'contact': 'contact',
        'decline_count': 'decline_count',
        'next_charge_date': 'next_charge_date',
        'updated_at': 'updated_at',
        'cc_token': 'cc_token',
        'cc_number': 'cc_number',
        'cc_exp': 'cc_exp'
    }

    def __init__(self, id=None, voip_id=None, status=None, nickname=None, type=None, created_at=None, contact=None, decline_count=None, next_charge_date=None, updated_at=None, cc_token=None, cc_number=None, cc_exp=None):
        """
        PaymentFull - a model defined in Swagger
        """

        self._id = None
        self._voip_id = None
        self._status = None
        self._nickname = None
        self._type = None
        self._created_at = None
        self._contact = None
        self._decline_count = None
        self._next_charge_date = None
        self._updated_at = None
        self._cc_token = None
        self._cc_number = None
        self._cc_exp = None

        if id is not None:
          self.id = id
        if voip_id is not None:
          self.voip_id = voip_id
        if status is not None:
          self.status = status
        if nickname is not None:
          self.nickname = nickname
        if type is not None:
          self.type = type
        if created_at is not None:
          self.created_at = created_at
        if contact is not None:
          self.contact = contact
        if decline_count is not None:
          self.decline_count = decline_count
        if next_charge_date is not None:
          self.next_charge_date = next_charge_date
        if updated_at is not None:
          self.updated_at = updated_at
        if cc_token is not None:
          self.cc_token = cc_token
        if cc_number is not None:
          self.cc_number = cc_number
        if cc_exp is not None:
          self.cc_exp = cc_exp

    @property
    def id(self):
        """
        Gets the id of this PaymentFull.
        Payment Method ID

        :return: The id of this PaymentFull.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this PaymentFull.
        Payment Method ID

        :param id: The id of this PaymentFull.
        :type: int
        """

        self._id = id

    @property
    def voip_id(self):
        """
        Gets the voip_id of this PaymentFull.
        API Account ID

        :return: The voip_id of this PaymentFull.
        :rtype: int
        """
        return self._voip_id

    @voip_id.setter
    def voip_id(self, voip_id):
        """
        Sets the voip_id of this PaymentFull.
        API Account ID

        :param voip_id: The voip_id of this PaymentFull.
        :type: int
        """

        self._voip_id = voip_id

    @property
    def status(self):
        """
        Gets the status of this PaymentFull.
        'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card;

        :return: The status of this PaymentFull.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this PaymentFull.
        'primary' = primary card used for billing; 'onfile' = card on file; 'hidden' = deleted card;

        :param status: The status of this PaymentFull.
        :type: str
        """

        self._status = status

    @property
    def nickname(self):
        """
        Gets the nickname of this PaymentFull.
        Name of Card

        :return: The nickname of this PaymentFull.
        :rtype: str
        """
        return self._nickname

    @nickname.setter
    def nickname(self, nickname):
        """
        Sets the nickname of this PaymentFull.
        Name of Card

        :param nickname: The nickname of this PaymentFull.
        :type: str
        """

        self._nickname = nickname

    @property
    def type(self):
        """
        Gets the type of this PaymentFull.
        'cc' for credit card

        :return: The type of this PaymentFull.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this PaymentFull.
        'cc' for credit card

        :param type: The type of this PaymentFull.
        :type: str
        """

        self._type = type

    @property
    def created_at(self):
        """
        Gets the created_at of this PaymentFull.
        Time payment record is created

        :return: The created_at of this PaymentFull.
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this PaymentFull.
        Time payment record is created

        :param created_at: The created_at of this PaymentFull.
        :type: int
        """

        self._created_at = created_at

    @property
    def contact(self):
        """
        Gets the contact of this PaymentFull.
        Detail of contact person

        :return: The contact of this PaymentFull.
        :rtype: ContactResponse
        """
        return self._contact

    @contact.setter
    def contact(self, contact):
        """
        Sets the contact of this PaymentFull.
        Detail of contact person

        :param contact: The contact of this PaymentFull.
        :type: ContactResponse
        """

        self._contact = contact

    @property
    def decline_count(self):
        """
        Gets the decline_count of this PaymentFull.
        Number of times the payment method was declined

        :return: The decline_count of this PaymentFull.
        :rtype: int
        """
        return self._decline_count

    @decline_count.setter
    def decline_count(self, decline_count):
        """
        Sets the decline_count of this PaymentFull.
        Number of times the payment method was declined

        :param decline_count: The decline_count of this PaymentFull.
        :type: int
        """

        self._decline_count = decline_count

    @property
    def next_charge_date(self):
        """
        Gets the next_charge_date of this PaymentFull.
        Next billing date

        :return: The next_charge_date of this PaymentFull.
        :rtype: int
        """
        return self._next_charge_date

    @next_charge_date.setter
    def next_charge_date(self, next_charge_date):
        """
        Sets the next_charge_date of this PaymentFull.
        Next billing date

        :param next_charge_date: The next_charge_date of this PaymentFull.
        :type: int
        """

        self._next_charge_date = next_charge_date

    @property
    def updated_at(self):
        """
        Gets the updated_at of this PaymentFull.
        Last time the payment method was updated

        :return: The updated_at of this PaymentFull.
        :rtype: int
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """
        Sets the updated_at of this PaymentFull.
        Last time the payment method was updated

        :param updated_at: The updated_at of this PaymentFull.
        :type: int
        """

        self._updated_at = updated_at

    @property
    def cc_token(self):
        """
        Gets the cc_token of this PaymentFull.
        Encrypted credit card token to be used for billing

        :return: The cc_token of this PaymentFull.
        :rtype: str
        """
        return self._cc_token

    @cc_token.setter
    def cc_token(self, cc_token):
        """
        Sets the cc_token of this PaymentFull.
        Encrypted credit card token to be used for billing

        :param cc_token: The cc_token of this PaymentFull.
        :type: str
        """

        self._cc_token = cc_token

    @property
    def cc_number(self):
        """
        Gets the cc_number of this PaymentFull.
        Credit card number partially masked with xxxxxxxx

        :return: The cc_number of this PaymentFull.
        :rtype: str
        """
        return self._cc_number

    @cc_number.setter
    def cc_number(self, cc_number):
        """
        Sets the cc_number of this PaymentFull.
        Credit card number partially masked with xxxxxxxx

        :param cc_number: The cc_number of this PaymentFull.
        :type: str
        """

        self._cc_number = cc_number

    @property
    def cc_exp(self):
        """
        Gets the cc_exp of this PaymentFull.
        Credit card expiration date

        :return: The cc_exp of this PaymentFull.
        :rtype: str
        """
        return self._cc_exp

    @cc_exp.setter
    def cc_exp(self, cc_exp):
        """
        Sets the cc_exp of this PaymentFull.
        Credit card expiration date

        :param cc_exp: The cc_exp of this PaymentFull.
        :type: str
        """

        self._cc_exp = cc_exp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PaymentFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
