# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class RedirectUriFull(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'uri': 'str',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'uri': 'uri',
        'type': 'type'
    }

    def __init__(self, id=None, uri=None, type=None):
        """
        RedirectUriFull - a model defined in Swagger
        """

        self._id = None
        self._uri = None
        self._type = None

        if id is not None:
          self.id = id
        if uri is not None:
          self.uri = uri
        if type is not None:
          self.type = type

    @property
    def id(self):
        """
        Gets the id of this RedirectUriFull.
        Redirect URI ID

        :return: The id of this RedirectUriFull.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this RedirectUriFull.
        Redirect URI ID

        :param id: The id of this RedirectUriFull.
        :type: int
        """

        self._id = id

    @property
    def uri(self):
        """
        Gets the uri of this RedirectUriFull.
        The Uniform Resource Identifier is a string used to identify the path to be redirected

        :return: The uri of this RedirectUriFull.
        :rtype: str
        """
        return self._uri

    @uri.setter
    def uri(self, uri):
        """
        Sets the uri of this RedirectUriFull.
        The Uniform Resource Identifier is a string used to identify the path to be redirected

        :param uri: The uri of this RedirectUriFull.
        :type: str
        """

        self._uri = uri

    @property
    def type(self):
        """
        Gets the type of this RedirectUriFull.
        redirect

        :return: The type of this RedirectUriFull.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this RedirectUriFull.
        redirect

        :param type: The type of this RedirectUriFull.
        :type: str
        """

        self._type = type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, RedirectUriFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
