# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ReplacePhoneNumberParams(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'route': 'object',
        'name': 'str',
        'block_incoming': 'str',
        'block_anonymous': 'str',
        'caller_id': 'CallerIdPhoneNumber',
        'sms_forwarding': 'SmsForwardingParams',
        'pool_item': 'object',
        'call_notifications': 'CallNotifications'
    }

    attribute_map = {
        'route': 'route',
        'name': 'name',
        'block_incoming': 'block_incoming',
        'block_anonymous': 'block_anonymous',
        'caller_id': 'caller_id',
        'sms_forwarding': 'sms_forwarding',
        'pool_item': 'pool_item',
        'call_notifications': 'call_notifications'
    }

    def __init__(self, route=None, name=None, block_incoming=None, block_anonymous=None, caller_id=None, sms_forwarding=None, pool_item=None, call_notifications=None):
        """
        ReplacePhoneNumberParams - a model defined in Swagger
        """

        self._route = None
        self._name = None
        self._block_incoming = None
        self._block_anonymous = None
        self._caller_id = None
        self._sms_forwarding = None
        self._pool_item = None
        self._call_notifications = None

        if route is not None:
          self.route = route
        if name is not None:
          self.name = name
        if block_incoming is not None:
          self.block_incoming = block_incoming
        if block_anonymous is not None:
          self.block_anonymous = block_anonymous
        if caller_id is not None:
          self.caller_id = caller_id
        if sms_forwarding is not None:
          self.sms_forwarding = sms_forwarding
        if pool_item is not None:
          self.pool_item = pool_item
        if call_notifications is not None:
          self.call_notifications = call_notifications

    @property
    def route(self):
        """
        Gets the route of this ReplacePhoneNumberParams.
        Route lookup object

        :return: The route of this ReplacePhoneNumberParams.
        :rtype: object
        """
        return self._route

    @route.setter
    def route(self, route):
        """
        Sets the route of this ReplacePhoneNumberParams.
        Route lookup object

        :param route: The route of this ReplacePhoneNumberParams.
        :type: object
        """

        self._route = route

    @property
    def name(self):
        """
        Gets the name of this ReplacePhoneNumberParams.
        Phone Name

        :return: The name of this ReplacePhoneNumberParams.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ReplacePhoneNumberParams.
        Phone Name

        :param name: The name of this ReplacePhoneNumberParams.
        :type: str
        """

        self._name = name

    @property
    def block_incoming(self):
        """
        Gets the block_incoming of this ReplacePhoneNumberParams.
        Block incoming calls

        :return: The block_incoming of this ReplacePhoneNumberParams.
        :rtype: str
        """
        return self._block_incoming

    @block_incoming.setter
    def block_incoming(self, block_incoming):
        """
        Sets the block_incoming of this ReplacePhoneNumberParams.
        Block incoming calls

        :param block_incoming: The block_incoming of this ReplacePhoneNumberParams.
        :type: str
        """

        self._block_incoming = block_incoming

    @property
    def block_anonymous(self):
        """
        Gets the block_anonymous of this ReplacePhoneNumberParams.
        Block anonymous calls

        :return: The block_anonymous of this ReplacePhoneNumberParams.
        :rtype: str
        """
        return self._block_anonymous

    @block_anonymous.setter
    def block_anonymous(self, block_anonymous):
        """
        Sets the block_anonymous of this ReplacePhoneNumberParams.
        Block anonymous calls

        :param block_anonymous: The block_anonymous of this ReplacePhoneNumberParams.
        :type: str
        """

        self._block_anonymous = block_anonymous

    @property
    def caller_id(self):
        """
        Gets the caller_id of this ReplacePhoneNumberParams.

        :return: The caller_id of this ReplacePhoneNumberParams.
        :rtype: CallerIdPhoneNumber
        """
        return self._caller_id

    @caller_id.setter
    def caller_id(self, caller_id):
        """
        Sets the caller_id of this ReplacePhoneNumberParams.

        :param caller_id: The caller_id of this ReplacePhoneNumberParams.
        :type: CallerIdPhoneNumber
        """

        self._caller_id = caller_id

    @property
    def sms_forwarding(self):
        """
        Gets the sms_forwarding of this ReplacePhoneNumberParams.

        :return: The sms_forwarding of this ReplacePhoneNumberParams.
        :rtype: SmsForwardingParams
        """
        return self._sms_forwarding

    @sms_forwarding.setter
    def sms_forwarding(self, sms_forwarding):
        """
        Sets the sms_forwarding of this ReplacePhoneNumberParams.

        :param sms_forwarding: The sms_forwarding of this ReplacePhoneNumberParams.
        :type: SmsForwardingParams
        """

        self._sms_forwarding = sms_forwarding

    @property
    def pool_item(self):
        """
        Gets the pool_item of this ReplacePhoneNumberParams.
        Pool lookup object

        :return: The pool_item of this ReplacePhoneNumberParams.
        :rtype: object
        """
        return self._pool_item

    @pool_item.setter
    def pool_item(self, pool_item):
        """
        Sets the pool_item of this ReplacePhoneNumberParams.
        Pool lookup object

        :param pool_item: The pool_item of this ReplacePhoneNumberParams.
        :type: object
        """

        self._pool_item = pool_item

    @property
    def call_notifications(self):
        """
        Gets the call_notifications of this ReplacePhoneNumberParams.

        :return: The call_notifications of this ReplacePhoneNumberParams.
        :rtype: CallNotifications
        """
        return self._call_notifications

    @call_notifications.setter
    def call_notifications(self, call_notifications):
        """
        Sets the call_notifications of this ReplacePhoneNumberParams.

        :param call_notifications: The call_notifications of this ReplacePhoneNumberParams.
        :type: CallNotifications
        """

        self._call_notifications = call_notifications

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ReplacePhoneNumberParams):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
