# coding: utf-8

"""
    Phone.com API

    This is a Phone.com api Swagger definition

    OpenAPI spec version: 1.0.0
    Contact: apisupport@phone.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class VoicemailFull(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'download_url': 'str',
        'extension': 'ExtensionSummary',
        '_from': 'FromObject',
        'to': 'str',
        'is_new': 'bool',
        'created_at': 'int',
        'folder': 'str',
        'duration': 'int'
    }

    attribute_map = {
        'id': 'id',
        'download_url': 'download_url',
        'extension': 'extension',
        '_from': 'from',
        'to': 'to',
        'is_new': 'is_new',
        'created_at': 'created_at',
        'folder': 'folder',
        'duration': 'duration'
    }

    def __init__(self, id=None, download_url=None, extension=None, _from=None, to=None, is_new=None, created_at=None, folder=None, duration=None):
        """
        VoicemailFull - a model defined in Swagger
        """

        self._id = None
        self._download_url = None
        self._extension = None
        self.__from = None
        self._to = None
        self._is_new = None
        self._created_at = None
        self._folder = None
        self._duration = None

        if id is not None:
          self.id = id
        if download_url is not None:
          self.download_url = download_url
        if extension is not None:
          self.extension = extension
        if _from is not None:
          self._from = _from
        if to is not None:
          self.to = to
        if is_new is not None:
          self.is_new = is_new
        if created_at is not None:
          self.created_at = created_at
        if folder is not None:
          self.folder = folder
        if duration is not None:
          self.duration = duration

    @property
    def id(self):
        """
        Gets the id of this VoicemailFull.
        Unique Voicemail ID. Read-only.

        :return: The id of this VoicemailFull.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this VoicemailFull.
        Unique Voicemail ID. Read-only.

        :param id: The id of this VoicemailFull.
        :type: str
        """

        self._id = id

    @property
    def download_url(self):
        """
        Gets the download_url of this VoicemailFull.
        Name. Required.

        :return: The download_url of this VoicemailFull.
        :rtype: str
        """
        return self._download_url

    @download_url.setter
    def download_url(self, download_url):
        """
        Sets the download_url of this VoicemailFull.
        Name. Required.

        :param download_url: The download_url of this VoicemailFull.
        :type: str
        """

        self._download_url = download_url

    @property
    def extension(self):
        """
        Gets the extension of this VoicemailFull.
        Extension where the voicemail is saved into.

        :return: The extension of this VoicemailFull.
        :rtype: ExtensionSummary
        """
        return self._extension

    @extension.setter
    def extension(self, extension):
        """
        Sets the extension of this VoicemailFull.
        Extension where the voicemail is saved into.

        :param extension: The extension of this VoicemailFull.
        :type: ExtensionSummary
        """

        self._extension = extension

    @property
    def _from(self):
        """
        Gets the _from of this VoicemailFull.
        The caller's information

        :return: The _from of this VoicemailFull.
        :rtype: FromObject
        """
        return self.__from

    @_from.setter
    def _from(self, _from):
        """
        Sets the _from of this VoicemailFull.
        The caller's information

        :param _from: The _from of this VoicemailFull.
        :type: FromObject
        """

        self.__from = _from

    @property
    def to(self):
        """
        Gets the to of this VoicemailFull.
        The phone number where the caller is calling

        :return: The to of this VoicemailFull.
        :rtype: str
        """
        return self._to

    @to.setter
    def to(self, to):
        """
        Sets the to of this VoicemailFull.
        The phone number where the caller is calling

        :param to: The to of this VoicemailFull.
        :type: str
        """

        self._to = to

    @property
    def is_new(self):
        """
        Gets the is_new of this VoicemailFull.
        True when Voicemail is new; False when Voicemail has been listened

        :return: The is_new of this VoicemailFull.
        :rtype: bool
        """
        return self._is_new

    @is_new.setter
    def is_new(self, is_new):
        """
        Sets the is_new of this VoicemailFull.
        True when Voicemail is new; False when Voicemail has been listened

        :param is_new: The is_new of this VoicemailFull.
        :type: bool
        """

        self._is_new = is_new

    @property
    def created_at(self):
        """
        Gets the created_at of this VoicemailFull.
        Date string representing the UTC time that the object was created in the Phone.com API system.

        :return: The created_at of this VoicemailFull.
        :rtype: int
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """
        Sets the created_at of this VoicemailFull.
        Date string representing the UTC time that the object was created in the Phone.com API system.

        :param created_at: The created_at of this VoicemailFull.
        :type: int
        """

        self._created_at = created_at

    @property
    def folder(self):
        """
        Gets the folder of this VoicemailFull.
        Folder name where voicemail is saved

        :return: The folder of this VoicemailFull.
        :rtype: str
        """
        return self._folder

    @folder.setter
    def folder(self, folder):
        """
        Sets the folder of this VoicemailFull.
        Folder name where voicemail is saved

        :param folder: The folder of this VoicemailFull.
        :type: str
        """

        self._folder = folder

    @property
    def duration(self):
        """
        Gets the duration of this VoicemailFull.
        Length of voicemail in seconds

        :return: The duration of this VoicemailFull.
        :rtype: int
        """
        return self._duration

    @duration.setter
    def duration(self, duration):
        """
        Sets the duration of this VoicemailFull.
        Length of voicemail in seconds

        :param duration: The duration of this VoicemailFull.
        :type: int
        """

        self._duration = duration

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, VoicemailFull):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
